[package]
name = "bin_tree"
version = "1.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
rand = { version = "0.8.5", optional = true }

[features]
default = []

[profile.test]
opt-level = 3
